//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usbechka_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public System.Guid id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
    }
}
