//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usbechka_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurant_usbechkaEntities : DbContext
    {
        public restaurant_usbechkaEntities()
            : base("name=restaurant_usbechkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<reserved_tables> reserved_tables { get; set; }
        public virtual DbSet<tables> tables { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
