//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usbechka_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
        public System.Guid table_id { get; set; }
        public System.TimeSpan time_end { get; set; }
        public string menu_ids { get; set; }
        public decimal full_price { get; set; }
        public System.DateTime payment_date { get; set; }
        public string payment_method { get; set; }
    
        public virtual tables tables { get; set; }
        public virtual users users { get; set; }
    }
}
