//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usbechka_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserved_tables
    {
        public System.Guid id { get; set; }
        public System.Guid table_id { get; set; }
        public System.Guid user_id { get; set; }
    
        public virtual tables tables { get; set; }
        public virtual users users { get; set; }
    }
}
