CREATE DATABASE restaurant_usbechka;

EXEC(
	'USE restaurant_usbechka;

	CREATE TABLE users (
		id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		phone VARCHAR(100) NOT NULL,
		password VARCHAR(255) NOT NULL,
		join_date DATETIME NOT NULL,
		role VARCHAR(20) NOT NULL
    );

	CREATE TABLE tables (
		id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		number_table INT NOT NULL,
		is_reserved BIT NOT NULL DEFAULT 0
    );

	CREATE TABLE orders (
		id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id),
		table_id UNIQUEIDENTIFIER NOT NULL REFERENCES tables(id),
		time_end TIME NOT NULL,
		menu_ids VARCHAR(MAX) NOT NULL,
		full_price DECIMAL(10, 2) NOT NULL,
		payment_date DATETIME NOT NULL DEFAULT GETDATE(),
		payment_method VARCHAR(50) NOT NULL
    );

	CREATE TABLE menu (
		id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		title VARCHAR(20) NOT NULL,
		description VARCHAR(100) NOT NULL,
		price DECIMAL(10, 2) NOT NULL
    );

	CREATE TABLE reserved_tables (
		id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
		table_id UNIQUEIDENTIFIER NOT NULL REFERENCES tables(id),
		user_id UNIQUEIDENTIFIER NOT NULL REFERENCES users(id)
    );

	'
);